N = 2

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vbox|
    vbox.memory = 1024
    vbox.cpus   = 2
  end

  (1..N).each do |i|
    config.vm.define "vpss-#{i}" do |vps|
      vps.vm.box = "sdg/centOS"
      vps.ssh.username = "sdg"
      vps.ssh.password = "sdg666"
      vps.vm.network "private_network", ip: "192.168.0.#{i + 10}"
      vps.vm.provision "file", source: "keys/sdg.pub", destination: "/home/sdg/sdg.pub"
      vps.vm.provision "shell",
      path: "pscr/sshd.sh",
      upload_path: "/home/sdg/sshd.sh"
      vps.vm.provision "shell",
      path: "pscr/net.sh",
      upload_path: "/home/sdg/net.sh"
      vps.vm.provision "shell",
      path: "pscr/hardening.sh",
      upload_path: "/home/sdg/hardening.sh"
    end
  end
end
