IMAGE_NAME = "bento/ubuntu-16.04"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.define "master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network",
                          ip: "192.168.50.10"
        master.vm.hostname = "master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "setup/master-playbook.yaml"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
            }
        end
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "setup/master-join-command.yaml"
        end
        master.vm.provision "ansible" do |cni|
            cni.playbook = "setup/master-cni-setup.yaml"
        end

    end

    (1..N).each do |i|
        config.vm.define "worker-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network",
                            ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "worker-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "setup/node-playbook.yaml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                }
                ansible.verbose = "true"
            end
        end
    end
end